-- Additive DDL: outbound/fulfillment fields on OutboundOrder (report v4.8).
-- Apply: npx prisma db execute --file prisma/_add-outbound-fulfillment-fields.sql
--
-- Why manual (not `prisma migrate`): migration history is stale (db push workflow); `migrate`
-- would see drift and could reset the shared Supabase DB (no git = unrecoverable).
-- All columns are nullable or boolean-with-default -> safe on existing rows. Idempotent.

ALTER TABLE "OutboundOrder"
  ADD COLUMN IF NOT EXISTS "shipperId" TEXT,
  ADD COLUMN IF NOT EXISTS "shipperNameZh" TEXT,
  ADD COLUMN IF NOT EXISTS "shipperNameEn" TEXT,
  ADD COLUMN IF NOT EXISTS "serviceName" TEXT,
  ADD COLUMN IF NOT EXISTS "serviceLocked" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "serviceUpdated" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "customerRef" TEXT,
  ADD COLUMN IF NOT EXISTS "platformRef" TEXT,
  ADD COLUMN IF NOT EXISTS "platformCode" TEXT,
  ADD COLUMN IF NOT EXISTS "orderSource" TEXT,
  ADD COLUMN IF NOT EXISTS "creator" TEXT,
  ADD COLUMN IF NOT EXISTS "inboundOrderNo" TEXT,
  ADD COLUMN IF NOT EXISTS "inboundContainerNo" TEXT,
  ADD COLUMN IF NOT EXISTS "trackingNo" TEXT,
  ADD COLUMN IF NOT EXISTS "trackingNo1" TEXT,
  ADD COLUMN IF NOT EXISTS "trackingTrace" TEXT,
  ADD COLUMN IF NOT EXISTS "trackingTrace1" TEXT,
  ADD COLUMN IF NOT EXISTS "carrier" TEXT,
  ADD COLUMN IF NOT EXISTS "multiPackage" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "recipientName" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientCompany" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientPhone" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientEmail" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientZip" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientCountry" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientProvince" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientCity" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientDistrict" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientAddress1" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientAddress2" TEXT,
  ADD COLUMN IF NOT EXISTS "recipientAddress3" TEXT,
  ADD COLUMN IF NOT EXISTS "shipToCode" TEXT,
  ADD COLUMN IF NOT EXISTS "addressType" TEXT,
  ADD COLUMN IF NOT EXISTS "remark" TEXT,
  ADD COLUMN IF NOT EXISTS "transactionAmount" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "transactionCurrency" TEXT,
  ADD COLUMN IF NOT EXISTS "fee" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "totalWeightKg" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS "totalVolumeCbm" DECIMAL(12,4),
  ADD COLUMN IF NOT EXISTS "packageLength" DECIMAL(8,1),
  ADD COLUMN IF NOT EXISTS "packageWidth" DECIMAL(8,1),
  ADD COLUMN IF NOT EXISTS "packageHeight" DECIMAL(8,1),
  ADD COLUMN IF NOT EXISTS "packageActualWeight" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS "packageBillingWeight" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS "packageActualVolume" DECIMAL(12,4),
  ADD COLUMN IF NOT EXISTS "pickingType" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "shippedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "exceptionReason" TEXT,
  ADD COLUMN IF NOT EXISTS "cancelResult" TEXT;
